### ISSUE TITLE
review

### ISSUE THREAD

**Issue by jordanlefort** [Laure-Milian/CV#1]
``` html
<div class="info_perso">

        <h1>Laure Milian</h1>
        <h5>En formation <strong>Développeur web et mobile</strong> à Simplon</h5>
        <h5>Webmarketing, gestion de projets web</h5>
        <h5>26 ans - Permis B - Toulouse</p></h5>

</div>
```

Essaie plutot de mettre ces infos en list : 

``` html
    <div class="info_perso">
      <ul>
        <li><h1>Laure Milian</h1></li>
        <li><h5>En formation <strong>Développeur web et mobile</strong> à Simplon</h5></li>
        <li><h5>Webmarketing, gestion de projets web</h5></li>
        <li><h5>26 ans - Permis B - Toulouse</p></h5></li>
     </ul>
    </div>
```

``` css
 .info_perso ul {
 margin:0;
padding:0;
list-style:none;
}

```

Pour les séparation (div.info_pero;div.competences) passe plutot par un schema comme celui-ci:

``` html
<header>

 </header>
 <section>

 </section>
 <footer>

 </footer>

```

``` html

    <h3><em>2016-2017</em> Développement web et mobile / Gestion de projets web</h3>
            <span><strong>Simplon.co</strong> - Toulouse, 6 mois</span>
```

Pour ceci si tu veut faire ressortir passe plutôt par  le css 

``` css
.tata {
font-style:oblique;
font-style:italic;
}
```
